services:
  app:
    build:
      context: .
      dockerfile: ./local.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - NODE_ENV=development
      # 環境変数は.envファイルから読み込まれます
    env_file:
      - .env
    command: bun run dev

volumes:
  node_modules:
